services:
  #####################
  # Postgres Database #
  #####################
  db:
    image: postgres:14-alpine
    container_name: django_db
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend_net

  #####################
  # Django Backend    #
  #####################
  backend:
    build: ./backend
    container_name: django_app
    # Run the Django dev server on port 8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app  # Bind mount our backend code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_HOST=db
    depends_on:
      - db
    networks:
      - backend_net

  #####################
  # React Frontend    #
  #####################
  frontend:
    build: ./frontend
    container_name: react_app
    # Bind mount our frontend code so changes are reflected
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - frontend_net

networks:
  backend_net:
  frontend_net:

volumes:
  db_data:
